# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeseosAduaneros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
    ]
