# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeseosAduaneros', '0002_personaje_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='imagen',
            field=models.CharField(blank=True, help_text='URL de la imagen del personaje', max_length=1000, verbose_name='Imágen'),
        ),
    ]
